version: 2
updates:
  # Allow all updates (major, minor, patch) in the develop branch
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      target-branch: develop
    open-pull-requests-limit: 2

  # Only allow minor and patch updates in release/* branches
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      target-branch: release/*
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
