<?php

declare(strict_types=1);

use PhpCsFixer\Config;
use PhpCsFixer\Runner\Parallel\ParallelConfigFactory;

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . '/examples')
    ->in(__DIR__ . '/src')
    ->in(__DIR__ . '/tests');

$rules = [
    'backtick_to_shell_exec' => true,
    'no_alias_language_construct_call' => true,
    'no_mixed_echo_print' => true,
    'array_syntax' => true,
    'no_multiline_whitespace_around_double_arrow' => true,
    'no_whitespace_before_comma_in_array' => true,
    'normalize_index_brace' => true,
    'trim_array_spaces' => true,
    'whitespace_after_comma_in_array' => true,
    'braces_position' => true,
    'encoding' => true,
    'no_multiple_statements_per_line' => true,
    'no_trailing_comma_in_singleline' => true,
    'octal_notation' => true,
    'class_reference_name_casing' => true,
    'constant_case' => true,
    'integer_literal_case' => true,
    'lowercase_keywords' => true,
    'lowercase_static_reference' => true,
    'magic_constant_casing' => true,
    'magic_method_casing' => true,
    'native_function_casing' => true,
    'native_type_declaration_casing' => true,
    'cast_spaces' => true,
    'lowercase_cast' => true,
    'no_short_bool_cast' => true,
    'no_unset_cast' => true,
    'short_scalar_cast' => true,
    'class_attributes_separation' => true,
    'class_definition' => ['single_line' => true, 'space_before_parenthesis' => true],
    'no_blank_lines_after_class_opening' => true,
    'no_null_property_initialization' => false,
    'ordered_class_elements' => true,
    'ordered_interfaces' => true,
    'protected_to_private' => true,
    'self_static_accessor' => true,
    'single_class_element_per_statement' => true,
    'single_trait_insert_per_statement' => true,
    'visibility_required' => true,
    'header_comment' => false,
    'multiline_comment_opening_closing' => true,
    'no_empty_comment' => true,
    'no_trailing_whitespace_in_comment' => true,
    'single_line_comment_spacing' => true,
    'single_line_comment_style' => true,
    'control_structure_braces' => true,
    'control_structure_continuation_position' => true,
    'elseif' => true,
    'empty_loop_body' => ['style' => 'braces'],
    'empty_loop_condition' => false,
    'include' => true,
    'no_alternative_syntax' => true,
    'no_break_comment' => true,
    'no_superfluous_elseif' => true,
    'no_unneeded_control_parentheses' => true,
    'no_unneeded_braces' => true,
    'no_useless_else' => true,
    'simplified_if_return' => true,
    'switch_case_semicolon_to_colon' => true,
    'switch_case_space' => true,
    'switch_continue_to_break' => true,
    'trailing_comma_in_multiline' => ['elements' => ['arguments', 'arrays', 'match', 'parameters']],
    'yoda_style' => ['equal' => false, 'identical' => false, 'less_and_greater' => false],
    'doctrine_annotation_array_assignment' => true,
    'doctrine_annotation_braces' => true,
    'doctrine_annotation_indentation' => true,
    'doctrine_annotation_spaces' => true,
    'function_declaration' => true,
    'type_declaration_spaces' => true,
    'lambda_not_used_import' => true,
    'method_argument_space' => true,
    'no_spaces_after_function_name' => true,
    'nullable_type_declaration_for_default_null_value' => true,
    'return_type_declaration' => true,
    'single_line_throw' => false,
    'fully_qualified_strict_types' => true,
    'global_namespace_import' => ['import_classes' => true, 'import_constants' => true, 'import_functions' => true],
    'group_import' => false,
    'no_leading_import_slash' => true,
    'no_unneeded_import_alias' => true,
    'no_unused_imports' => true,
    'ordered_imports' => ['imports_order' => ['class', 'function', 'const'], 'sort_algorithm' => 'alpha'],
    'single_import_per_statement' => true,
    'single_line_after_imports' => true,
    'combine_consecutive_issets' => true,
    'combine_consecutive_unsets' => true,
    'declare_equal_normalize' => true,
    'declare_parentheses' => true,
    'explicit_indirect_variable' => true,
    'single_space_around_construct' => true,
    'list_syntax' => ['syntax' => 'short'],
    'blank_line_after_namespace' => true,
    'clean_namespace' => true,
    'blank_lines_before_namespace' => true,
    'no_leading_namespace_whitespace' => true,
    'assign_null_coalescing_to_coalesce_equal' => true,
    'binary_operator_spaces' => true,
    'concat_space' => ['spacing' => 'one'],
    'increment_style' => false,
    'new_with_parentheses' => true,
    'no_space_around_double_colon' => true,
    'no_useless_concat_operator' => true,
    'no_useless_nullsafe_operator' => true,
    'not_operator_with_space' => false,
    'not_operator_with_successor_space' => false,
    'object_operator_without_whitespace' => true,
    'operator_linebreak' => true,
    'standardize_increment' => true,
    'standardize_not_equals' => true,
    'ternary_operator_spaces' => true,
    'ternary_to_null_coalescing' => true,
    'unary_operator_spaces' => true,
    'blank_line_after_opening_tag' => true,
    'echo_tag_syntax' => true,
    'full_opening_tag' => true,
    'linebreak_after_opening_tag' => true,
    'no_closing_tag' => true,
    'php_unit_fqcn_annotation' => true,
    'php_unit_internal_class' => false,
    'php_unit_method_casing' => true,
    'php_unit_size_class' => false,
    'php_unit_test_class_requires_covers' => false,
    'align_multiline_comment' => ['comment_type' => 'all_multiline'],
    'general_phpdoc_annotation_remove' => false,
    'general_phpdoc_tag_rename' => ['replacements' => ['inheritDocs' => 'inheritDoc']],
    'no_blank_lines_after_phpdoc' => true,
    'no_empty_phpdoc' => true,
    'no_superfluous_phpdoc_tags' => ['allow_mixed' => false, 'allow_unused_params' => false],
    'phpdoc_add_missing_param_annotation' => true,
    'phpdoc_align' => ['align' => 'left'],
    'phpdoc_annotation_without_dot' => true,
    'phpdoc_indent' => true,
    'phpdoc_inline_tag_normalizer' => true,
    'phpdoc_line_span' => ['method' => 'multi', 'const' => 'single', 'property' => 'single'],
    'phpdoc_no_access' => true,
    'phpdoc_no_alias_tag' => true,
    'phpdoc_no_empty_return' => false,
    'phpdoc_no_package' => true,
    'phpdoc_no_useless_inheritdoc' => true,
    'phpdoc_order_by_value' => false,
    'phpdoc_order' => ['order' => ['param', 'return', 'throws']],
    'phpdoc_return_self_reference' => true,
    'phpdoc_scalar' => true,
    'phpdoc_separation' => true,
    'phpdoc_single_line_var_spacing' => true,
    'phpdoc_summary' => true,
    'phpdoc_tag_casing' => false,
    'phpdoc_tag_type' => false,
    'phpdoc_to_comment' => false,
    'phpdoc_trim_consecutive_blank_line_separation' => true,
    'phpdoc_trim' => true,
    'phpdoc_types' => true,
    'phpdoc_types_order' => true,
    'phpdoc_var_annotation_correct_order' => true,
    'phpdoc_var_without_name' => true,
    'no_useless_return' => true,
    'return_assignment' => true,
    'simplified_null_return' => true,
    'multiline_whitespace_before_semicolons' => true,
    'no_empty_statement' => true,
    'no_singleline_whitespace_before_semicolons' => true,
    'semicolon_after_instruction' => true,
    'space_after_semicolon' => true,
    'declare_strict_types' => true,
    'string_implicit_backslashes' => true,
    'explicit_string_variable' => true,
    'heredoc_to_nowdoc' => false,
    'no_binary_string' => true,
    'simple_to_complex_string_variable' => true,
    'single_quote' => true,
    'array_indentation' => true,
    'blank_line_before_statement' => [
        'statements' => [
            'break',
            'case',
            'continue',
            'declare',
            'default',
            'exit',
            'goto',
            'include',
            'include_once',
            'phpdoc',
            'require',
            'require_once',
            'return',
            'switch',
            'throw',
            'try',
            'yield',
            'yield_from',
        ],
    ],
    'compact_nullable_type_declaration' => true,
    'heredoc_indentation' => true,
    'indentation_type' => true,
    'line_ending' => true,
    'method_chaining_indentation' => true,
    'no_extra_blank_lines' => [
        'tokens' => [
            'attribute',
            'case',
            'continue',
            'curly_brace_block',
            'default',
            'extra',
            'parenthesis_brace_block',
            'square_brace_block',
            'switch',
            'throw',
            'use',
        ],
    ],
    'no_spaces_around_offset' => true,
    'spaces_inside_parentheses' => ['space' => 'none'],
    'no_trailing_whitespace' => true,
    'no_whitespace_in_blank_line' => true,
    'single_blank_line_at_eof' => true,
    'statement_indentation' => true,
    'types_spaces' => true,
];

return (new Config())
    ->setParallelConfig(ParallelConfigFactory::detect())
    ->setFinder($finder)
    ->setRiskyAllowed(true)
    ->setRules($rules)
    ->setLineEnding("\n");
