name: Parse Next Version
description: Determine next release version

outputs:
  release_branch:
    description: The release branch
  release_version:
    description: The release version

runs:
  using: composite
  steps:
    - name: Determine next version
      shell: bash
      run: |
        branch=$(make print-branch)
        version=$(make print-version)
        
        echo "release_branch=${branch}" >> $GITHUB_ENV
        echo "release_version=${version}" >> $GITHUB_ENV
